Repository add-ons/plugin.video.yelo, pull requests merged in 2020-06, with the labels that each got.

#17 Fix pylint checks
  resources/lib/iptvmanager.py
  resources/lib/yelo.py
  resources/lib/yelo_api.py
Labels: testing

#18 Attempt to fix tests without credentials
  .github/workflows/ci.yml
Labels: testing

#15 Add IPTV Manager integration in the add-on settings
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/settings.xml
Labels: enhancement

#19 Add README badges
  README.md
Labels: documentation

#21 Fix data transfers over 1 MB to IPTV Manager
  resources/lib/iptvmanager.py
Labels: bug

#22 Device registration for Play subscription
  resources/lib/helpers/helpermethods.py
  resources/lib/yelo_api.py
Labels: bug
